### ISSUE TITLE
Updated scene list

### ISSUE THREAD

**Issue by Glennmen** [nilsreiter/home-assistant-scenes#10]
I found this scene preset list that seems more up to date than the gist file -> https://github.com/Hypfer/hass-scene_presets/blob/master/custom_components/scene_presets/presets.json
It does seem to be in a different format so you would probably have to change your json parsing script 😅 

I would also filter out the `Misc Additions` category, these seem custom to that project.

**Comment by Glennmen** [comment]
@nilsreiter If interested I can see if I can work our a script that parses that json and gives the same outcome as your convert.py script.

**Comment by Glennmen** [comment]
I have tried to run your convert.py script locally, only thing I haven't been able to figure out is how you get the single line json output that you use in ha-scenes.yaml.
https://github.com/nilsreiter/home-assistant-scenes/blob/cb3005b3a8031ff4d8eff6cbac45268fcc89d02d/ha-scenes.yaml#L546-L551

**Comment by nilsreiter** [comment]
That was manual post-processing using regular expressions in my text editor.
