### ISSUE TITLE
Is it possible to pass in a series of custom colors?

### ISSUE THREAD

**Issue by dmfrey** [nilsreiter/home-assistant-scenes#15]
I'd like to use this but pass in a custom set of colors. For instance, I'd like to setup the colors of my favorite Hockey or Football team and have dynamic scene affects with the team's colors when they are playing.

Is that possible? Is that what the colorloop is for?

**Comment by Glennmen** [comment]
That is currently not supported but should be fairly straightforward to implement.

**Comment by nilsreiter** [comment]
Yes, should be. How many colors are we talking?

**Comment by dmfrey** [comment]
Most teams only have 2 or 3 colors.

**Comment by nilsreiter** [comment]
It is now in 3.3. You'll need the color info in XY form. [This](https://viereck.ch/hue-xy-rgb/) should work for conversion/selection.

**Comment by nilsreiter** [comment]
Oh, and I found this for looking up team colors: https://teamcolorcodes.com

**Comment by dmfrey** [comment]
This is great news! I'll try this later tonight when I'm home.

Thank you so much.

**Comment by dmfrey** [comment]
So far, seems to be working great when I manually trigger them. Now I'm gonna add them to my automation. 

Quick question...
Under `my_scene`, there are `c` and `b` keys. I get that `c` is the color list in xy notation. Is `b` brightness? something else? I noticed on the xy calculator you posted, it converted sRGB to x, y and bri. does it equate to the `bri`? If so, do they need to go with their respective colors?
