### ISSUE TITLE
Magneto wrong naming

### ISSUE THREAD

**Issue by ChiyoDragon** [nilsreiter/home-assistant-scenes#4]
I wanted to point out a small typo I noticed. The scene is currently named "Magneto" but it should be "Magento." This correction would help avoid any confusion.

Thank you for your hard work and dedication. Keep up the fantastic job!

**Comment by ChiyoDragon** [comment]
Added a PR for it 😄 #5

**Comment by nilsreiter** [comment]
Oh thanks, I hadn't noticed the typo. Will merge over the weekend.

**Comment by nilsreiter** [comment]
@ChiyoDragon Could you please verify that the scene is called Magento in your Hue app? In mine, it actually is called Magneto, but this could also be different scenes.
