### ISSUE TITLE
Feature request: Also add default scenes and brightness

### ISSUE THREAD

**Issue by Glennmen** [nilsreiter/home-assistant-scenes#7]
I am also in the process of migrating all my Hue devices from my bridge to HA and manually creating all the scenes for each room/group is a real pain 😅 
Discovered this script today and it looks awesome.

Would it be possible to add the default scenes too, listed in the same [gist file](https://gist.github.com/Hypfer/a0a8b5b9429831a7306ec4300077eaaa). This would help me a lot with setting up my automations that I use with motion sensors.

Also as an addition would it be possible to add the default brightness for each scene from that gist, of course as a default that will be overridden when you set a custom value in the data object.

**Comment by nilsreiter** [comment]
All done in 3.0 :)
