### ISSUE TITLE
How to install and set up?

### ISSUE THREAD

**Issue by GLehnhoff** [nilsreiter/home-assistant-scenes#8]
I am looking for something like that but I have no idea what to do to get this up and running, what to install, where to install, how to install, etc. A guide for users (and not experts) would be helpful.

**Comment by nilsreiter** [comment]
I cannot provide a full-fledged guide, but can give you pointers: Essentially, what this repo provides is a script blueprint. These are documented [here](https://www.home-assistant.io/docs/blueprint/), and an installation guide can be found [here](https://community.home-assistant.io/t/about-blueprints/253788).

The easiest installation method is to click the button in [this forum post](https://community.home-assistant.io/t/dynamic-hue-like-color-scenes-with-randomly-distributed-colors/714013).
