### ISSUE TITLE
Lights being filtered out

### ISSUE THREAD

**Issue by Glennmen** [nilsreiter/home-assistant-scenes#9]
After playing around with the script I noticed it wasn't triggering some of my lights, after investing some time debugging my lights and area setup I went through the code of the script and noticed that it filtered out lights that don't have colormode `xy` or `rgb`.

These lights only have colormode `color_temp`
I adjusted the script to not filter them out and it seems to be working fine. Of course some scenes might look "weird" but if you use the "Default" scene set it should work perfectly.

Not sure if it was filtered out intentionally or not.

**Comment by nilsreiter** [comment]
My understanding of `color_temp` was that it doesn't support colors, so it didn't make sense to me to include those. But you're right, with the default scenes, it makes sense to include them.
